name = "legal-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

routes = [
  { pattern = "ahkam.app", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "egypt-judgments"
database_id = "22485ae3-e83c-47c5-8181-0b50f4129eb1"